// vue-todo/src/TodoInput.vue
<template>
  <input v-model="todo" type="text" />
  <button @click="handleSave">Save</button>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const todo = ref('');
const emit = defineEmits(['save']);
const handleSave = () => {
  if (!todo.value) return;
  emit('save', todo.value);
  todo.value = '';
};
</script>

// react-todo/src/TodoInput.tsx
import { ChangeEvent, useState } from 'react';

function TodoInput({ onSave }: { onSave: (todo: string) => void }) {
  const [todo, setTodo] = useState('');

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    setTodo(event.target.value);
  };

  const handleSave = () => {
    if (!todo) return;
    setTodo('');
    onSave(todo);
  };

  return (
    <>
      <input value={todo} type="text" onChange={handleInput} />
      <button onClick={handleSave}>Save</button>
    </>
  );
}

export default TodoInput;
